$:
  vscode:
    - runner:
        cpus: 1
      services:
        - vscode
        - docker

.github-sync: &github-sync
  runner:
    cpus: 1
  env:
    GITHUB_REPO: https://github.com/Womsxd/MihoyoBBSTools.git
  stages:
    - name: sync
      script: |
        git remote add github "${GITHUB_REPO}" || git remote set-url github "${GITHUB_REPO}"
        git fetch github --prune --tags --force
        git push origin --all --force
        git push origin --tags --force


master:
  "crontab: 0 6 * * *": 
    - *github-sync
  web_trigger_sync: 
    - *github-sync
